# Generated by Django 4.0.6 on 2022-07-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('donor', 'donor'), ('recipient', 'recipient'), ('admin', 'admin')], max_length=20),
        ),
    ]
