# Generated by Django 4.0.6 on 2022-09-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_account_type_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center_name',
            field=models.CharField(blank=True, help_text='Name of hospital, center or blood bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('donor', 'donor'), ('donation_center', 'donation_center'), ('admin', 'admin')], max_length=20),
        ),
    ]
