# Generated by Django 4.0.6 on 2022-09-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_center_name_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center_name',
            field=models.CharField(blank=True, help_text='Name of hospital, center or blood bank', max_length=500),
        ),
    ]
