# Generated by Django 4.1.1 on 2023-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_gender_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.BigIntegerField(choices=[(5133, 'admin'), (4758, 'editor'), (3214, 'customer service'), (2033, 'low staff'), (1155, 'end user')], default=1155),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('donor', 'donor'), ('donation_center', 'donation_center')], max_length=20),
        ),
    ]
