# Generated by Django 4.0.6 on 2022-08-31 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('accepted', 'accepted')], default=('pending', 'pending'), max_length=10)),
                ('reason_for_decline', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('blood_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_center', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
