# Generated by Django 4.1.1 on 2022-12-04 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsBlood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('blood_type', models.CharField(choices=[('nil', 'nil'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=('nil', 'nil'), max_length=10)),
                ('gender', models.CharField(choices=[('nil', 'nil'), ('male', 'male'), ('female', 'female')], default=('nil', 'nil'), max_length=10)),
                ('center', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
