# Generated by Django 4.1.1 on 2023-02-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_requestsblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval',
            field=models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('accepted', 'accepted')], default=('pending', 'pending'), max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('completed', 'completed')], default=('pending', 'pending'), max_length=12),
        ),
    ]
