# Generated by Django 4.1.1 on 2023-01-24 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVisitors',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('useragent', models.CharField(blank=True, max_length=500)),
                ('fingerprint', models.CharField(blank=True, max_length=150)),
                ('browser', models.CharField(blank=True, max_length=150)),
                ('browser_type', models.CharField(blank=True, max_length=150)),
                ('desktop', models.BooleanField(default=False)),
                ('desktop_device', models.CharField(blank=True, max_length=150)),
                ('desktop_device_type', models.CharField(blank=True, max_length=150)),
                ('mobile', models.BooleanField(default=False)),
                ('mobile_device', models.CharField(blank=True, max_length=150)),
                ('mobile_device_type', models.CharField(blank=True, max_length=150)),
                ('ip', models.CharField(blank=True, max_length=150)),
                ('vpn', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('language', models.CharField(blank=True, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
